[package]
name = "my-project"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

[lib]
name = "helper_funcs"
path = "src/lib/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
